export const mockArtists = [
  {
    id: 1,
    name: "Sarah Johnson",
    category: "singers",
    location: "New York, NY",
    priceRange: "$500-$1500",
    rating: 4.9,
    reviews: 45,
    image:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Professional jazz and pop vocalist with 10+ years of experience performing at weddings, corporate events, and concerts.",
    languages: ["English", "Spanish"],
    specialties: ["Jazz", "Pop", "Soul", "Wedding Songs"],
    experience: "10+ years",
    availability: "available",
  },
  {
    id: 2,
    name: "Dance Fusion Crew",
    category: "dancers",
    location: "Los Angeles, CA",
    priceRange: "$800-$2000",
    rating: 4.8,
    reviews: 32,
    image: "https://images.unsplash.com/photo-1547153760-18fc86324498?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Award-winning dance crew specializing in contemporary fusion and hip-hop choreography for events and competitions.",
    languages: ["English"],
    specialties: ["Hip Hop", "Contemporary", "Breakdance", "Choreography"],
    experience: "8+ years",
    availability: "available",
  },
  {
    id: 3,
    name: "DJ Mike Stevens",
    category: "djs",
    location: "Miami, FL",
    priceRange: "$400-$1200",
    rating: 4.9,
    reviews: 67,
    image:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Professional DJ with expertise in electronic music, weddings, and corporate events. State-of-the-art equipment included.",
    languages: ["English", "Portuguese"],
    specialties: ["Electronic", "House", "Wedding", "Corporate Events"],
    experience: "12+ years",
    availability: "available",
  },
  {
    id: 4,
    name: "Marcus Thompson",
    category: "speakers",
    location: "Chicago, IL",
    priceRange: "$1000-$3000",
    rating: 4.7,
    reviews: 28,
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Motivational speaker and business coach with expertise in leadership development and team building.",
    languages: ["English"],
    specialties: ["Motivational Speaking", "Leadership", "Team Building", "Corporate Training"],
    experience: "15+ years",
    availability: "busy",
  },
  {
    id: 5,
    name: "Elena Rodriguez",
    category: "singers",
    location: "Austin, TX",
    priceRange: "$600-$1800",
    rating: 4.8,
    reviews: 39,
    image:
      "https://images.unsplash.com/photo-1494790108755-2616c9c0e8e0?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Bilingual singer specializing in Latin music, pop, and acoustic performances for intimate and large-scale events.",
    languages: ["English", "Spanish"],
    specialties: ["Latin", "Pop", "Acoustic", "Bilingual"],
    experience: "7+ years",
    availability: "available",
  },
  {
    id: 6,
    name: "The Rhythm Collective",
    category: "dancers",
    location: "Seattle, WA",
    priceRange: "$700-$1800",
    rating: 4.6,
    reviews: 24,
    image:
      "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Professional dance troupe specializing in cultural dances and modern choreography for festivals and events.",
    languages: ["English"],
    specialties: ["Cultural Dance", "Modern", "Festival Performances", "Group Choreography"],
    experience: "6+ years",
    availability: "available",
  },
  {
    id: 7,
    name: "DJ Luna",
    category: "djs",
    location: "Las Vegas, NV",
    priceRange: "$500-$1500",
    rating: 4.9,
    reviews: 52,
    image:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Female DJ specializing in EDM, pop, and party music. Perfect for clubs, parties, and high-energy events.",
    languages: ["English"],
    specialties: ["EDM", "Pop", "Party Music", "Club Events"],
    experience: "9+ years",
    availability: "available",
  },
  {
    id: 8,
    name: "Dr. Amanda Foster",
    category: "speakers",
    location: "Boston, MA",
    priceRange: "$1200-$4000",
    rating: 4.8,
    reviews: 35,
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&q=80",
    bio: "Keynote speaker and author focusing on innovation, technology, and women in leadership.",
    languages: ["English"],
    specialties: ["Keynote Speaking", "Innovation", "Technology", "Women in Leadership"],
    experience: "20+ years",
    availability: "available",
  },
]

export const categories = [
  { value: "all", label: "All Categories" },
  { value: "singers", label: "Singers" },
  { value: "dancers", label: "Dancers" },
  { value: "speakers", label: "Speakers" },
  { value: "djs", label: "DJs" },
]

export const locations = [
  { value: "all", label: "All Locations" },
  { value: "New York, NY", label: "New York, NY" },
  { value: "Los Angeles, CA", label: "Los Angeles, CA" },
  { value: "Miami, FL", label: "Miami, FL" },
  { value: "Chicago, IL", label: "Chicago, IL" },
  { value: "Austin, TX", label: "Austin, TX" },
  { value: "Seattle, WA", label: "Seattle, WA" },
  { value: "Las Vegas, NV", label: "Las Vegas, NV" },
  { value: "Boston, MA", label: "Boston, MA" },
]

export const priceRanges = [
  { value: "all", label: "All Price Ranges" },
  { value: "$0-$500", label: "Under $500" },
  { value: "$500-$1000", label: "$500 - $1,000" },
  { value: "$1000-$2000", label: "$1,000 - $2,000" },
  { value: "$2000+", label: "$2,000+" },
]
